services:
  db:
    image: postgres:15-alpine 
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: nikita        
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: library_db        
    ports:
      - "5433:5432" # Стандартный порт PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data # Правильный путь для сохранения данных Postgres
    networks:         
      - custom_net    

  library:
    build: .
    image: necrofus/library
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:         
      - custom_net
volumes:
  pgdata: # Переименовали esdata1 во что-то более понятное
    driver: local
networks:             
  custom_net:         
    driver: bridge    